excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Karayel.github.io
name: 1 Year Software Challange
description: This is my personal blog and its shows that what am I planning to learn in 1 year. Related to this challenge,I wanna take some notes.<br /><br />Challenge begins...<br /><br />11-07-2016 / 11-07-????
author: Karayel
avatar: https://avatars3.githubusercontent.com/u/7863112?v=3&s=460
ga_domain: 
ga_tracking_id: 
