title: Mert KARAYEL
description: My Personal Blog
author: Mert KARAYEL
logo: /static/img/avatar.png
github: https://github.com/Karayel
about: Software Engineer at Netaş

baseurl: ""
url: ""

disqus_shortname: karayel
google_analytics: UA-83043986-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 8
per_page: 8
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
